---
title: "R Leslie Matrix Example"
author: "Wylie Hampson"
date: "8/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Creating matrices in R

Use the `matrix()` function to wrap a series of values (a vector) into a matrix.

- Use `nrow = ` to specify number of rows
- Use `ncol = ` to specift number of columns
- Use `byrow = TRUE` to populate the matrix by ROWS instead of columns

```{r}
cats <- c(1, 3, 5, 8, 10, 0.2, 4, 8, 10, 11, 100)

# Wrap cats into a matrix

cat_matrix <- matrix(data = cats, nrow = 4, ncol = 5, byrow = TRUE)
```

```{r}
dogs <- matrix(data = c(1, 0, 2, 3), nrow = 2, ncol = 2, byrow = TRUE)

rats <- matrix(data = c(5, 7, 2, 10), nrow = 2, ncol = 2, byrow = TRUE)

horses <- matrix(data = c(15, 17, 2, 1.5), nrow = 2, ncol = 2, byrow = TRUE)

horses %*% rats
```

## Create the Leslie Matrix

```{r}
insect_leslie <- matrix(data = c( 0, 0, 600, 0.2, 0,  0, 0, 0.08, 0.6), nrow = 3,
                              ncol = 3, byrow = TRUE)

# Specify the initial conditions
# What is the population in each life stage at year 0?
insect_y0 <- c(12000, 700, 500)

# Project the population in each life stage for year 1
insect_y1 <- insect_leslie %*% insect_y0

# Project the population in each life stage for years 2, 3, and 4
insect_y2 <- insect_leslie %*% insect_y1
insect_y3 <- insect_leslie %*% insect_y2
insect_y4 <- insect_leslie %*% insect_y3

insect_y1
insect_y2
insect_y3
insect_y4
```





